import React, { useState } from 'react';
import {
  Bot,
  ShieldCheck,
  Zap,
  RotateCcw,
  Code,
  CheckCircle2,
  Clock,
  Sliders,
  Cpu,
  FileCode,
  Copy,
  Check,
} from 'lucide-react';
import { AIAgent } from '../../types/cyber';

interface AIAgentsViewProps {
  agents: AIAgent[];
  onToggleAutopilot: (agentId: string) => void;
}

export const AIAgentsView: React.FC<AIAgentsViewProps> = ({
  agents,
  onToggleAutopilot,
}) => {
  const [selectedPatch, setSelectedPatch] = useState<string>('sshd');
  const [copied, setCopied] = useState<boolean>(false);

  const samplePatches: Record<string, string> = {
    sshd: `# Sentinel AI - Autogenerated SSH Configuration Patch
# Applied for CVE-2026-1189 Mitigation
Port 2022
PermitRootLogin no
MaxAuthTries 3
PasswordAuthentication no
PubkeyAuthentication yes
AllowUsers soc_analyst lead_responder
ClientAliveInterval 300
ClientAliveCountMax 2
# IPTables drop rule generated by Vanguard Response Agent
iptables -A INPUT -p tcp -s 185.220.101.42 --dport 22 -j DROP`,

    dockerfile: `# Sentinel AI - Hardened Container Dockerfile Patch
FROM alpine:3.19
RUN apk add --no-cap-sys-admin --no-cache shadow ca-certificates
RUN useradd -u 10001 -m -s /bin/false appuser
USER appuser
# Disable SUID/SGID bit permissions
RUN find / -perm /6000 -type f -exec chmod a-s {} + 2>/dev/null || true
HEALTHCHECK --interval=30s --timeout=3s CMD wget --spider http://localhost:8080/health || exit 1
ENTRYPOINT ["/app/microservice"]`,

    fail2ban: `# Sentinel AI - Fail2ban Security Jail
[sshd-hardened]
enabled = true
port = ssh,2022
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
findtime = 600
bantime = 86400
action = iptables-multiport[name=SSH, port="ssh,2022", protocol=tcp]`,
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6 overflow-y-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <h1 className="text-xl font-bold font-mono text-slate-100 flex items-center gap-2">
            <Bot className="w-5 h-5 text-cyan-400" />
            <span>AUTONOMOUS AI DEFENSE AGENTS ENGINE</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Real-time orchestration of 4 specialized AI agents working in tandem for detection, isolation, recovery, and patch generation.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono px-3 py-1.5 rounded-lg bg-cyan-950/60 border border-cyan-500/40 text-cyan-300">
          <Cpu className="w-4 h-4 text-cyan-400" />
          <span>GEMINI 3.6 FLASH REASONING ENGINE ACTIVE</span>
        </div>
      </div>

      {/* Agents Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {agents.map((agent) => (
          <div
            key={agent.id}
            className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-4 hover:border-cyan-500/40 transition-all"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-cyan-950 border border-cyan-800 flex items-center justify-center text-cyan-400 font-bold font-mono">
                  {agent.role === 'detection' ? 'DET' : agent.role === 'response' ? 'RES' : agent.role === 'recovery' ? 'REC' : 'PAT'}
                </div>
                <div>
                  <h2 className="text-sm font-bold text-slate-100 font-mono">
                    {agent.name}
                  </h2>
                  <p className="text-[11px] text-slate-400">{agent.description}</p>
                </div>
              </div>

              {/* Autopilot Switch */}
              <button
                onClick={() => onToggleAutopilot(agent.id)}
                className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-mono font-bold border transition-colors ${
                  agent.autoPilotEnabled
                    ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                    : 'bg-slate-800 text-slate-400 border-slate-700'
                }`}
              >
                <div className={`w-2 h-2 rounded-full ${agent.autoPilotEnabled ? 'bg-emerald-400 animate-pulse' : 'bg-slate-500'}`} />
                <span>{agent.autoPilotEnabled ? 'AUTOPILOT ON' : 'MANUAL'}</span>
              </button>
            </div>

            {/* Last Action Box */}
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800/80 space-y-1">
              <span className="text-[10px] font-mono text-slate-500">LAST EXECUTED DEFENSIVE ACTION</span>
              <p className="text-xs text-slate-200 font-mono leading-snug">
                {agent.lastAction}
              </p>
              <span className="text-[10px] text-cyan-400 font-mono block pt-1">
                {agent.lastActionTimestamp}
              </span>
            </div>

            {/* Agent Stats */}
            <div className="grid grid-cols-2 gap-3 text-xs font-mono">
              <div className="p-2.5 rounded-lg bg-slate-950 border border-slate-800">
                <span className="text-[10px] text-slate-500">ACTIONS COMPLETED</span>
                <p className="font-bold text-slate-200 mt-0.5">{agent.actionsTakenCount}</p>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-950 border border-slate-800">
                <span className="text-[10px] text-slate-500 font-mono">AVG CONFIDENCE</span>
                <p className="font-bold text-emerald-400 mt-0.5">{agent.confidenceAvg}%</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Generated Patch Code Inspector Section */}
      <div className="p-6 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-4">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 pb-3 border-b border-slate-800">
          <div className="flex items-center gap-2">
            <FileCode className="w-5 h-5 text-cyan-400" />
            <h2 className="text-sm font-bold font-mono text-slate-100">
              CIPHER PATCH GENERATOR — AUTOMATED REMEDIATION SCRIPTS
            </h2>
          </div>

          <div className="flex items-center gap-2">
            {['sshd', 'dockerfile', 'fail2ban'].map((type) => (
              <button
                key={type}
                onClick={() => setSelectedPatch(type)}
                className={`px-3 py-1 rounded-lg text-xs font-mono font-bold border transition-colors uppercase ${
                  selectedPatch === type
                    ? 'bg-cyan-950 border-cyan-500 text-cyan-300'
                    : 'bg-slate-950 border-slate-800 text-slate-400 hover:text-slate-200'
                }`}
              >
                {type}
              </button>
            ))}

            <button
              onClick={() => handleCopy(samplePatches[selectedPatch])}
              className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-200 text-xs font-mono transition-colors ml-2"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Code'}</span>
            </button>
          </div>
        </div>

        <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-emerald-400 font-mono text-xs overflow-x-auto leading-relaxed">
          {samplePatches[selectedPatch]}
        </pre>
      </div>
    </div>
  );
};
