import React, { useState } from 'react';
import { FileCheck, Download, Printer, Shield, CheckCircle2, FileText, Zap } from 'lucide-react';
import { jsPDF } from 'jspdf';

export const SecurityReports: React.FC = () => {
  const [generating, setGenerating] = useState<string | null>(null);

  const reportTypes = [
    {
      id: 'executive',
      title: 'SOC Executive Security Summary',
      description: 'C-level brief outlining total attack volume, risk score index, AI containment SLA, and security posture.',
    },
    {
      id: 'forensic',
      title: 'Incident Forensic Investigation Report',
      description: 'Detailed forensic breakdown of database ransomware intrusion, log artifacts, evidence hashes, and MITRE mapping.',
    },
    {
      id: 'threat_intel',
      title: 'Threat Intelligence & IOC Audit',
      description: 'Comprehensive feed report of tracked malicious IPs, C2 domains, LockBit hashes, and APT29 profiles.',
    },
    {
      id: 'vulnerability',
      title: 'Network Vulnerability Assessment',
      description: 'Audit of open ports, unpatched CVEs, configuration flaws, and autogenerated remediation checklists.',
    },
  ];

  const handleGeneratePDF = (reportId: string, title: string) => {
    setGenerating(reportId);

    setTimeout(() => {
      const doc = new jsPDF();

      // Title Header
      doc.setFillColor(8, 47, 73); // Dark cyan
      doc.rect(0, 0, 210, 30, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('SENTINEL AI - CYBER DEFENSE REPORT', 14, 18);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated: ${new Date().toLocaleString()} | Classification: CONFIDENTIAL`, 14, 25);

      // Report Name
      doc.setTextColor(2, 132, 199);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(title, 14, 45);

      // Section 1: Executive Overview
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('1. EXECUTIVE SUMMARY & SOC STATUS', 14, 58);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('• Network Risk Index: 64/100 (Elevated Threat State)', 18, 66);
      doc.text('• Total Cyber Attacks Intercepted: 364 Events (24 Hours)', 18, 72);
      doc.text('• AI Containment Response SLA: 1.2 Seconds (99.2% Automated Rate)', 18, 78);
      doc.text('• Active Quarantined Containers: 1 Node (Docker Sandbox Isolated)', 18, 84);

      // Section 2: Key Incident Details
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('2. CRITICAL INCIDENT FORENSIC BREAKDOWN', 14, 100);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('Incident Title: High-Frequency SSH Brute Force & Credential Dumping', 18, 108);
      doc.text('Target Node: DB-Cluster-PostgreSQL (10.0.2.20)', 18, 114);
      doc.text('Attacker IP: 185.220.101.42 (Tor Exit Node / APT29 Co-location)', 18, 120);
      doc.text('MITRE ATT&CK Technique: T1110.001 - Password Guessing', 18, 126);

      // Section 3: AI Defensive Actions Taken
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('3. AUTONOMOUS AI DEFENSE AGENT ACTIONS', 14, 142);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('[Aegis Detection Agent] Identified 4,201 SSH PAM failures in 30s with 99.2% confidence.', 18, 150);
      doc.text('[Vanguard Response Agent] Executed automated iptables DROP rule for IP 185.220.101.42.', 18, 156);
      doc.text('[Cipher Patch Agent] Autogenerated sshd_config hardening patch & fail2ban jail.', 18, 162);
      doc.text('[Phoenix Recovery Agent] Verified PostgreSQL DB snapshot integrity SHA256.', 18, 168);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text('Sentinel AI Autonomous Cyber Defense Laboratory • All rights reserved.', 14, 280);

      doc.save(`sentinel_${reportId}_report.pdf`);
      setGenerating(null);
    }, 1200);
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6 overflow-y-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <h1 className="text-xl font-bold font-mono text-slate-100 flex items-center gap-2">
            <FileCheck className="w-5 h-5 text-cyan-400" />
            <span>SECURITY REPORTS & COMPLIANCE GENERATOR</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Generate printable PDF executive summaries, forensic incident audits, and vulnerability compliance reports.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono px-3 py-1.5 rounded-lg bg-emerald-950/60 border border-emerald-500/40 text-emerald-300">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          <span>PDF GENERATOR READY</span>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reportTypes.map((rep) => (
          <div
            key={rep.id}
            className="p-6 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-4 hover:border-cyan-500/40 transition-all flex flex-col justify-between"
          >
            <div>
              <div className="flex items-center gap-2 text-cyan-400 font-bold font-mono text-xs mb-2">
                <FileText className="w-4 h-4" />
                <span>CYBER AUDIT TEMPLATE</span>
              </div>
              <h2 className="text-base font-bold font-mono text-slate-100">
                {rep.title}
              </h2>
              <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                {rep.description}
              </p>
            </div>

            <button
              onClick={() => handleGeneratePDF(rep.id, rep.title)}
              disabled={generating === rep.id}
              className="w-full py-3 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold font-mono text-xs shadow-lg shadow-cyan-950 flex items-center justify-center gap-2 transition-all"
            >
              <Download className="w-4 h-4" />
              <span>
                {generating === rep.id ? 'GENERATING PDF REPORT...' : 'DOWNLOAD PDF REPORT'}
              </span>
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
